[providers]
java = "17"

[phases.build]
dependsOn = ["setup"]
cmds = ["./mvnw clean package -DskipTests"]

[phases.setup]
nixPkgs = ["maven", "openjdk17"]
cmds = ["chmod +x ./mvnw"]

[start]
cmd = "java -jar target/Color-craze-0.0.1-SNAPSHOT.jar"