[providers]
java = "17"

[variables]
JAVA_VERSION = "17"
JDK_VERSION = "17"
MAVEN_OPTS = "-Djava.version=17 -Dmaven.compiler.source=17 -Dmaven.compiler.target=17 -Dmaven.compiler.release=17"

[phases.setup]
nixPkgs = ["maven", "openjdk17"]
cmds = ["chmod +x ./mvnw"]

[phases.build]
dependsOn = ["setup"]
cmds = [
  "java -version",
  "javac -version", 
  "mvn -version",
  "./mvnw clean install -DskipTests -Dmaven.compiler.source=17 -Dmaven.compiler.target=17 -Dmaven.compiler.release=17"
]

[start]
cmd = "java -jar target/Color-craze-0.0.1-SNAPSHOT.jar"