[build]
builder = "nixpacks"

[deploy]
startCommand = "java -jar target/Color-craze-0.0.1-SNAPSHOT.jar"
healthcheckPath = "/actuator/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10