[build]
builder = "nixpacks"

[build.nixpacksConfig]
providers = ["java"]

[deploy]
startCommand = "java -jar target/Color-craze-0.0.1-SNAPSHOT.jar"
# Usar un healthcheck que no dependa de Mongo mientras se habilita la red en Atlas
healthcheckPath = "/api/test/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10