[build]
builder = "nixpacks"

[build.nixpacksConfig]
providers = ["java"]

[deploy]
startCommand = "java -jar target/Color-craze-0.0.1-SNAPSHOT.jar"
# Healthcheck est√°ndar de Actuator
healthcheckPath = "/actuator/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10